table D_Clients
	lineageTag: af1fcb0e-4e75-4eae-a2ce-15400203fb4f

	measure Measures = { 1 }
		formatString: 0
		lineageTag: 9684ba6e-aab5-42c0-91fb-525e92923cc8

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 9a7f2ee8-6e47-4144-8931-f05856a63162
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column ClientNom
		dataType: string
		lineageTag: 242473c8-11b7-4f63-a12d-682bac9201b6
		summarizeBy: none
		sourceColumn: ClientNom

		annotation SummarizationSetBy = Automatic

	column SegmentClient
		dataType: string
		lineageTag: a35c1af9-6e2f-4584-8557-3558e4bfafa4
		summarizeBy: none
		sourceColumn: SegmentClient

		annotation SummarizationSetBy = Automatic

	column Ville
		dataType: string
		lineageTag: cd9edcd4-3a02-4dea-ba8b-f86afb87db10
		summarizeBy: none
		sourceColumn: Ville

		annotation SummarizationSetBy = Automatic

	partition D_Clients = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\claud\OneDrive\Bureau\PowerBI-Versionning\dataTest.xlsx"), null, true),
				    Clients_Sheet = Source{[Item="Clients",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Clients_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ClientID", Int64.Type}, {"ClientNom", type text}, {"SegmentClient", type text}, {"Ville", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

