table F_Ventes
	lineageTag: e91cb77c-583d-4440-bb5f-3991126928c9

	column VenteID
		dataType: int64
		formatString: 0
		lineageTag: ef08b763-15a1-4543-b906-adb899c3cf18
		summarizeBy: count
		sourceColumn: VenteID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 473bed37-2088-4c71-8efb-c0df3ac64e57
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProduitID
		dataType: int64
		formatString: 0
		lineageTag: bb837775-0e3a-4963-a33a-e2647e184b1e
		summarizeBy: none
		sourceColumn: ProduitID

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: a772dd86-65ca-4136-b9a0-2bb354c26641
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: a59ebea2-b63f-4c77-8e31-ee3c7a8df9da
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column Quantite
		dataType: int64
		formatString: 0
		lineageTag: 288ca56b-d51b-4cec-b3d7-d80c94dd9458
		summarizeBy: sum
		sourceColumn: Quantite

		annotation SummarizationSetBy = Automatic

	column PrixUnitaire
		dataType: int64
		formatString: 0
		lineageTag: 0e8703ce-07b7-4fea-adaa-d9ce87475e92
		summarizeBy: sum
		sourceColumn: PrixUnitaire

		annotation SummarizationSetBy = Automatic

	column CoutUnitaire
		dataType: int64
		formatString: 0
		lineageTag: 7628aca9-359f-4aed-a1ce-7320563358df
		summarizeBy: sum
		sourceColumn: CoutUnitaire

		annotation SummarizationSetBy = Automatic

	partition F_Ventes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\claud\OneDrive\Bureau\test\dataTest.xlsx"), null, true),
				    Ventes_Sheet = Source{[Item="Ventes",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Ventes_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"VenteID", Int64.Type}, {"Date", type date}, {"ProduitID", Int64.Type}, {"ClientID", Int64.Type}, {"RegionID", Int64.Type}, {"Quantite", Int64.Type}, {"PrixUnitaire", Int64.Type}, {"CoutUnitaire", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

